### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by nikagl** [Modjor/SickAdd#1]
No issue, just a comment. Works as a charm on Windows 2010. Had to manually install lxml first Here's the instructions:

Download lxml-3.4.4-cp27-none-win_amd64.whl from here: 
http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

Run this command:
pip install lxml-3.4.4-cp27-none-win_amd64.whl

Install SickAdd:
git clone https://github.com/Modjor/SickAdd
cd SickAdd
SickAdd.py

And off course, use the task scheduler to schedule this task to retrieve your TVDB favorites and IMDB watchlists!

**Comment by Modjor** [comment]
Thanks for the update & infos @nikagl - much appreciated :)
