### ISSUE TITLE
Support Trakt.tv

### ISSUE THREAD

**Issue by Miloune** [Modjor/SickAdd#2]
Hello,

First of all, thanks for this :)
It's possible to add the same things for watchlist from Trakt.tv?

Thanks you in advance.
Miloune

**Comment by Modjor** [comment]
Hi,

Why would you want to add this to SickAdd, as importing watchlist from Track.tv is already supported natively in Sickbeard/Sickrage?

- closing the request. Feel fee to reopen it if you think I missed the point.
