### ISSUE TITLE
IMDb no longer uses rss. Parse csv instead?

### ISSUE THREAD

**Issue by kinged007** [Modjor/SickAdd#3]
Hi, thanks for the great script!

Any chance you can modify it to parse the csv created by IMDb instead of RSS feed, since IMDb no longer create RSS feeds?

That would be awesome!!?

Thanks

**Comment by Modjor** [comment]
Hi,

Are you sure...? My watchlist are still available in RSS?

http://rss.imdb.com/user/urxxxxxxxxx/watchlist still works for me

modjor

**Comment by kinged007** [comment]
You right, thanks. The link to RSS is not on the site, or Im missing that
too.
QUick question, it is now working with the RSS feed, but it does not
download the first season like my default settings say it should do.... Any
advice?

Thanks

ᐧ

**Comment by Modjor** [comment]
SickAdd only takes care of adding the show to your Sickeard/Sickrage/SickGear... 
So if the show appears in your Show list in Sickbeard, but does not download, most likely you got an issue with SickBeard.

Make sure the episode you want are shown as wanted, look at the sickbeard logs to see what sickbeard is doing etc...

But you ll have to bring this issue to the team supporting the Sickbeard fork you are using

Closing issue as resolved
